<?php

declare(strict_types=1);

namespace App\Enums;

enum UserActionEnum: string
{
    case AccountCreation = 'account_created';
    case AccountUpdate = 'account_updated';
    case AccountDeletion = 'account_deleted';
    case MemberInvited = 'member_invited';
    case InvitationAccepted = 'invitation_accepted';
    case MemberRemoved = 'member_removed';
    case MemberRoleUpdated = 'member_role_updated';
    case CatalogCreation = 'collection_created';
    case CatalogUpdate = 'collection_updated';
    case CatalogDeletion = 'collection_deleted';
    case CatalogTypeCreation = 'collection_type_created';
    case CatalogTypeUpdate = 'collection_type_updated';
    case CatalogTypeDeletion = 'collection_type_deleted';
    case CustomFieldCreation = 'custom_field_created';
    case CustomFieldUpdate = 'custom_field_updated';
    case CustomFieldDeletion = 'custom_field_deleted';
    case CustomFieldGroupCreation = 'custom_field_group_created';
    case CustomFieldGroupUpdate = 'custom_field_group_updated';
    case CustomFieldGroupDeletion = 'custom_field_group_deleted';
    case ItemCreation = 'item_created';
    case ItemUpdate = 'item_updated';
    case ItemDeletion = 'item_deleted';
    case ItemPhotoCreation = 'item_photo_created';
    case ItemPhotoUpdate = 'item_photo_updated';
    case ItemPhotoDeletion = 'item_photo_deleted';
    case ItemTagAttached = 'item_tag_attached';
    case ItemTagDetached = 'item_tag_detached';
    case CopyCreation = 'copy_created';
    case CopyUpdate = 'copy_updated';
    case CopyDeletion = 'copy_deleted';
    case CopyMoved = 'copy_moved';
    case TransactionCreation = 'transaction_created';
    case TransactionUpdate = 'transaction_updated';
    case TransactionDeletion = 'transaction_deleted';
    case ProvenanceEventCreation = 'provenance_event_created';
    case ProvenanceEventUpdate = 'provenance_event_updated';
    case ProvenanceEventDeletion = 'provenance_event_deleted';
    case ValuationCreation = 'valuation_created';
    case ValuationUpdate = 'valuation_updated';
    case ValuationDeletion = 'valuation_deleted';
    case InsuranceRecordCreation = 'insurance_record_created';
    case InsuranceRecordUpdate = 'insurance_record_updated';
    case InsuranceRecordDeletion = 'insurance_record_deleted';
    case MaintenanceRecordCreation = 'maintenance_record_created';
    case MaintenanceRecordUpdate = 'maintenance_record_updated';
    case MaintenanceRecordDeletion = 'maintenance_record_deleted';
    case LoanCreation = 'loan_created';
    case LoanUpdate = 'loan_updated';
    case LoanReturn = 'loan_returned';
    case LoanDeletion = 'loan_deleted';
    case DocumentUpload = 'document_uploaded';
    case DocumentUpdate = 'document_updated';
    case DocumentDeletion = 'document_deleted';
    case LocationCreation = 'location_created';
    case LocationUpdate = 'location_updated';
    case LocationDeletion = 'location_deleted';
    case ConditionCreation = 'condition_created';
    case ConditionUpdate = 'condition_updated';
    case ConditionDeletion = 'condition_deleted';
    case TagCreation = 'tag_created';
    case TagUpdate = 'tag_updated';
    case TagDeletion = 'tag_deleted';
    case CategoryCreation = 'category_created';
    case CategoryUpdate = 'category_updated';
    case CategoryDeletion = 'category_deleted';
    case SetCreation = 'set_created';
    case SetUpdate = 'set_updated';
    case SetDeletion = 'set_deleted';
    case SeriesCreation = 'series_created';
    case SeriesUpdate = 'series_updated';
    case SeriesDeletion = 'series_deleted';
    case GettingStartedUpdate = 'getting_started_updated';
    case TrashRestoration = 'trash_restored';
    case TrashEmptied = 'trash_emptied';
    case ApiKeyCreation = 'api_key_created';
    case ApiKeyDeletion = 'api_key_deleted';
    case WebhookEndpointCreation = 'webhook_endpoint_created';
    case WebhookEndpointDeletion = 'webhook_endpoint_deleted';
    case SupportTicketCreation = 'support_ticket_created';
    case SupportTicketUpdate = 'support_ticket_updated';
    case SupportTicketDeletion = 'support_ticket_deleted';
    case SupportMessageCreation = 'support_message_created';
    case SupportMessageUpdate = 'support_message_updated';
    case SupportMessageDeletion = 'support_message_deleted';
    case MagicLinkCreated = 'magic_link_created';
    case PersonalProfileUpdate = 'user_profile_updated';
    case AvatarUpdate = 'user_avatar_updated';
    case AvatarDeletion = 'user_avatar_deleted';
    case UpdateUserPassword = 'user_password_updated';
    case AutoDeleteUserUpdate = 'user_auto_delete_updated';
    case TwoFaQrCodeGeneration = '2fa_qr_generated';
    case TwoFaRemoval = '2fa_removed';
    case InstanceAccountDeletion = 'instance_account_deleted';
    case InstanceUserDeletion = 'instance_user_deleted';
    case InstanceAdministratorUpdate = 'instance_administrator_updated';
    case TestimonialSubmitted = 'testimonial_submitted';
    case TestimonialWithdrawn = 'testimonial_withdrawn';
    case TestimonialPublished = 'testimonial_published';
    case TestimonialRejected = 'testimonial_rejected';
    case BlogPostCreation = 'blog_post_created';
    case BlogPostUpdate = 'blog_post_updated';
    case BlogPostDeletion = 'blog_post_deleted';
    case BlogPostPublished = 'blog_post_published';
    case BlogPostArchived = 'blog_post_archived';
    case BlogPostTranslationUpdate = 'blog_post_translation_updated';
    case BlogPostTranslationStateUpdate = 'blog_post_translation_state_updated';
    case BlogPostOgImageUpdate = 'blog_post_og_image_updated';
    case BlogPostOgImageDeletion = 'blog_post_og_image_deleted';
    case SiteOptionsUpdate = 'site_options_updated';
    case CloudflareCachePurged = 'cloudflare_cache_purged';
    case PurchaseConsentRecorded = 'purchase_consent_recorded';

    public function translationKey(): string
    {
        return match ($this) {
            self::AccountCreation => 'Created an account',
            self::AccountUpdate => 'Updated the account called :name',
            self::AccountDeletion => 'Deleted the account called :name',
            self::MemberInvited => 'Invited :email to the account',
            self::InvitationAccepted => 'Joined the account called :name',
            self::MemberRemoved => 'Removed a member from the account',
            self::MemberRoleUpdated => 'Updated a member\'s role to :role',
            self::CatalogCreation => 'Created the collection called :name',
            self::CatalogUpdate => 'Updated the collection called :name',
            self::CatalogDeletion => 'Deleted the collection called :name',
            self::CatalogTypeCreation => 'Created the collection type called :name',
            self::CatalogTypeUpdate => 'Updated the collection type called :name',
            self::CatalogTypeDeletion => 'Deleted the collection type called :name',
            self::CustomFieldCreation => 'Created the custom field called :name',
            self::CustomFieldUpdate => 'Updated the custom field called :name',
            self::CustomFieldDeletion => 'Deleted the custom field called :name',
            self::CustomFieldGroupCreation => 'Created the field group called :name',
            self::CustomFieldGroupUpdate => 'Updated the field group called :name',
            self::CustomFieldGroupDeletion => 'Deleted the field group called :name',
            self::ItemCreation => 'Created the item called :name',
            self::ItemUpdate => 'Updated the item called :name',
            self::ItemDeletion => 'Deleted the item called :name',
            self::ItemPhotoCreation => 'Added a photo to the item called :name',
            self::ItemPhotoUpdate => 'Updated a photo of the item called :name',
            self::ItemPhotoDeletion => 'Deleted a photo of the item called :name',
            self::ItemTagAttached => 'Added the tag :tag to the item called :name',
            self::ItemTagDetached => 'Removed the tag :tag from the item called :name',
            self::CopyCreation => 'Added a copy of the item called :name',
            self::CopyUpdate => 'Updated a copy of the item called :name',
            self::CopyDeletion => 'Deleted a copy of the item called :name',
            self::CopyMoved => 'Moved a copy of the item called :name',
            self::TransactionCreation => 'Recorded a transaction on the item called :name',
            self::TransactionUpdate => 'Updated a transaction on the item called :name',
            self::TransactionDeletion => 'Deleted a transaction on the item called :name',
            self::ProvenanceEventCreation => 'Recorded a provenance event on the item called :name',
            self::ProvenanceEventUpdate => 'Updated a provenance event on the item called :name',
            self::ProvenanceEventDeletion => 'Deleted a provenance event on the item called :name',
            self::ValuationCreation => 'Recorded a valuation on the item called :name',
            self::ValuationUpdate => 'Updated a valuation on the item called :name',
            self::ValuationDeletion => 'Deleted a valuation on the item called :name',
            self::InsuranceRecordCreation => 'Recorded an insurance record on the item called :name',
            self::InsuranceRecordUpdate => 'Updated an insurance record on the item called :name',
            self::InsuranceRecordDeletion => 'Deleted an insurance record on the item called :name',
            self::MaintenanceRecordCreation => 'Logged a maintenance record on the item called :name',
            self::MaintenanceRecordUpdate => 'Updated a maintenance record on the item called :name',
            self::MaintenanceRecordDeletion => 'Deleted a maintenance record on the item called :name',
            self::LoanCreation => 'Recorded a loan on the item called :name',
            self::LoanUpdate => 'Updated a loan on the item called :name',
            self::LoanReturn => 'Marked a loan as returned on the item called :name',
            self::LoanDeletion => 'Deleted a loan on the item called :name',
            self::DocumentUpload => 'Attached a document to the item called :name',
            self::DocumentUpdate => 'Updated a document on the item called :name',
            self::DocumentDeletion => 'Deleted a document from the item called :name',
            self::LocationCreation => 'Created the location called :name',
            self::LocationUpdate => 'Updated the location called :name',
            self::LocationDeletion => 'Deleted the location called :name',
            self::ConditionCreation => 'Created the condition called :name',
            self::ConditionUpdate => 'Updated the condition called :name',
            self::ConditionDeletion => 'Deleted the condition called :name',
            self::TagCreation => 'Created the tag called :name',
            self::TagUpdate => 'Updated the tag called :name',
            self::TagDeletion => 'Deleted the tag called :name',
            self::CategoryCreation => 'Created the category called :name',
            self::CategoryUpdate => 'Updated the category called :name',
            self::CategoryDeletion => 'Deleted the category called :name',
            self::SetCreation => 'Created the set called :name',
            self::SetUpdate => 'Updated the set called :name',
            self::SetDeletion => 'Deleted the set called :name',
            self::SeriesCreation => 'Created the series called :name',
            self::SeriesUpdate => 'Updated the series called :name',
            self::SeriesDeletion => 'Deleted the series called :name',
            self::GettingStartedUpdate => 'Updated the getting started screen to :status',
            self::TrashRestoration => 'Restored the :type called :name from the trash',
            self::TrashEmptied => 'Emptied the trash, permanently deleting :count objects',
            self::ApiKeyCreation => 'Created an API key',
            self::ApiKeyDeletion => 'Deleted an API key',
            self::WebhookEndpointCreation => 'Created a webhook endpoint',
            self::WebhookEndpointDeletion => 'Deleted a webhook endpoint',
            self::SupportTicketCreation => 'Opened a support conversation',
            self::SupportTicketUpdate => 'Updated a support conversation',
            self::SupportTicketDeletion => 'Deleted a support conversation',
            self::SupportMessageCreation => 'Replied to a support conversation',
            self::SupportMessageUpdate => 'Edited a support message',
            self::SupportMessageDeletion => 'Deleted a support message',
            self::MagicLinkCreated => 'Sent a magic link',
            self::PersonalProfileUpdate => 'Updated their personal profile',
            self::AvatarUpdate => 'Updated their avatar',
            self::AvatarDeletion => 'Removed their avatar',
            self::UpdateUserPassword => 'Updated their password',
            self::AutoDeleteUserUpdate => 'Updated auto delete account setting to :status',
            self::TwoFaQrCodeGeneration => 'Generated 2FA QR code for setup',
            self::TwoFaRemoval => 'Removed 2FA from account',
            self::InstanceAccountDeletion => 'Deleted the account called :name from the instance administration',
            self::InstanceUserDeletion => 'Deleted the user :email from the instance administration',
            self::InstanceAdministratorUpdate => 'Instance administration :status for :email',
            self::TestimonialSubmitted => 'Submitted a testimonial for the marketing site',
            self::TestimonialWithdrawn => 'Withdrew their testimonial from the marketing site',
            self::TestimonialPublished => 'Published the testimonial by :name on the marketing site',
            self::TestimonialRejected => 'Rejected the testimonial by :name',
            self::BlogPostCreation => 'Started the blog entry :reference',
            self::BlogPostUpdate => 'Updated the blog entry :reference',
            self::BlogPostDeletion => 'Deleted the blog entry :reference',
            self::BlogPostPublished => 'Published the blog entry :reference',
            self::BlogPostArchived => 'Archived the blog entry :reference',
            self::BlogPostTranslationUpdate => 'Edited the :locale text of the blog entry :reference',
            self::BlogPostTranslationStateUpdate => 'Changed how far along the :locale text of the blog entry :reference is',
            self::BlogPostOgImageUpdate => 'Replaced the :locale social card of the blog entry :reference',
            self::BlogPostOgImageDeletion => 'Removed the :locale social card of the blog entry :reference',
            self::SiteOptionsUpdate => 'Updated the site options from the instance administration',
            self::CloudflareCachePurged => 'Purged the Cloudflare cache from the instance administration',
            self::PurchaseConsentRecorded => 'Confirmed the terms of unlocking the account',
        };
    }
}
